server:
  port: 8110 # 服务端口
  tomcat:
    max-threads: 10 #tomcat的最大并发值修改为10,默认是200

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-edu # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_guli_edu?serverTimezone=GMT%2B8
    username: root
    password: sa123456
#spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
    sentinel:
      transport:
        port: 8081 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8080 # 指定控制台服务的地址
  redis:
    #host: 192.168.100.100
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456 #默认为空
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/guli/service/edu/mapper/xml/*.xml

# 设置日志级别
#logging:
#  level:
#    root: INFO

#service-oss: # 调用的提供者的名称 service-product
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 第一次请求失败的话，会再发起4-1=3次重试(转到下一台机器时的第一次被当做首次调用，当也叫为重试）
#ribbon:
#  MaxAutoRetries: 1 # 同一实例最大重试次数，不包括首次调用，默认0
#  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数（服务器的转移次数），不包括首次所选的server，默认1
ribbon:
  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒 （5000为5秒）
  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒

  feign:
    sentinel:
      enabled: true